# site settings
title: Ambeep
subtitle: for audiobook narrators
email: info@ambeep.com
description: Recording software for audiobook narrators.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

google_script_url: https://script.google.com/macros/s/AKfycbwuj9l23YEssEEqcjfVfGroH93HaKbtripT_ssV/exec

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 0 # 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/AmbeepFace/
github_url: https://github.com/ambeep
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/AmbeepTweets

# build settings
markdown: kramdown

sass:
  style: compressed
